// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcJQ39hV3qbelavRd2RvtoxbCrjDyPBTI',
    appId: '1:122274903593:web:6a59d00c29057266100e38',
    messagingSenderId: '122274903593',
    projectId: 'safe-chat-bd918',
    authDomain: 'safe-chat-bd918.firebaseapp.com',
    storageBucket: 'safe-chat-bd918.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsCnxyI_2GnxNo3dLqnaVKxWgfcB9o0DQ',
    appId: '1:122274903593:android:e80d5fa820b43e2d100e38',
    messagingSenderId: '122274903593',
    projectId: 'safe-chat-bd918',
    storageBucket: 'safe-chat-bd918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWOVrdE4Q_i3exp8dYPzYfGF6yBZa6QTc',
    appId: '1:122274903593:ios:5c7f92d21f940d6c100e38',
    messagingSenderId: '122274903593',
    projectId: 'safe-chat-bd918',
    storageBucket: 'safe-chat-bd918.firebasestorage.app',
    iosBundleId: 'com.example.safeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWOVrdE4Q_i3exp8dYPzYfGF6yBZa6QTc',
    appId: '1:122274903593:ios:5c7f92d21f940d6c100e38',
    messagingSenderId: '122274903593',
    projectId: 'safe-chat-bd918',
    storageBucket: 'safe-chat-bd918.firebasestorage.app',
    iosBundleId: 'com.example.safeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcJQ39hV3qbelavRd2RvtoxbCrjDyPBTI',
    appId: '1:122274903593:web:839c855d6f8953ee100e38',
    messagingSenderId: '122274903593',
    projectId: 'safe-chat-bd918',
    authDomain: 'safe-chat-bd918.firebaseapp.com',
    storageBucket: 'safe-chat-bd918.firebasestorage.app',
  );
}
